In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
data = pd.read_csv("../data/housing.csv")

In [10]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

data info is all about tell us all data how many rows and which type of data stored in there

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

so as we say in total_bedrooms has missing 200 values which is not clean for ml

In [14]:
data.dropna(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB

In [17]:
from sklearn.model_selection import train_test_split

In [26]:
X = data.drop(["median_house_value"],axis=1)
Y = data["median_house_value"]

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
train_data = X_train.join(Y_train)

In [31]:
train_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
3715,-118.41,34.19,39.0,1169.0,242.0,612.0,247.0,4.1429,<1H OCEAN,200000.0
5438,-118.43,34.01,31.0,2526.0,528.0,1046.0,504.0,4.7009,<1H OCEAN,500001.0
5060,-118.35,34.00,28.0,3085.0,621.0,1162.0,558.0,3.2500,<1H OCEAN,301000.0
19563,-120.95,37.59,29.0,1727.0,439.0,1063.0,386.0,1.8929,INLAND,63600.0
12124,-117.24,33.94,15.0,1569.0,423.0,1123.0,369.0,1.6111,INLAND,113900.0
...,...,...,...,...,...,...,...,...,...,...
20577,-121.94,38.89,15.0,1462.0,314.0,774.0,271.0,2.5478,INLAND,91700.0
1241,-121.91,39.03,48.0,1096.0,218.0,657.0,199.0,2.7841,INLAND,65800.0
9013,-118.67,34.16,17.0,16544.0,2206.0,6214.0,2118.0,9.1228,<1H OCEAN,500001.0
20609,-121.56,39.11,18.0,2171.0,480.0,1527.0,447.0,2.3011,INLAND,57500.0
18674,-121.90,36.97,21.0,3707.0,751.0,1420.0,608.0,4.4485,NEAR OCEAN,295200.0